version: '3.4'
services:
  webapp:
    image: rusok/centralizadorapi
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASNETCORE_HTTPS_PORT: "8001"
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/